### ISSUE TITLE
After performing pihole -r, whitelist and blacklist are empty under the Domain Management page

### ISSUE THREAD

**Issue by byungkim** [pi-hole/pi-hole#3748]
### Versions

Pi-hole version is v5.1.2 (Latest: v5.1.2)
AdminLTE version is v5.1.1 (Latest: v5.1.1)
FTL version is v5.2 (Latest: v5.2)

### Platform

- OS and version:  Debian Buster

- Platform:  Raspberry Pi

### Expected behavior

After running 'pihole -r' to modify my IP, I should be able to see the whitelist and blacklist in the Admin console under the Domain Management page

### Actual behavior / bug

Domain management page does not display preconfigured whitelist and blacklist 

### Steps to reproduce

1. New pihole install with whitelist and blacklist entries populated.
2. Run 'pihole -r' and modify IP
3. Go to admin page and look at whitelist and blacklist
4. Whitelist and blacklist are empty

## Debug Token

- URL:  https://tricorder.pi-hole.net/u9wtqmc2ob

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by jfb-pihole** [comment]
Have you cleared the browser cache and reloaded the page?

**Comment by yubiuser** [comment]
Did you select `repair` or `reconfigure`?

**Comment by ottoxgam** [comment]
Confirming similar behavior after selecting `repair`

**Comment by dschaper** [comment]
Have you cleared the browser cache and reloaded the page?

**Comment by ottoxgam** [comment]
Yes. I've cleared cache as well as tried private browsing and different browsers.

**Comment by dschaper** [comment]
A debug token would show more information, without one there's not much more we can do.

**Comment by ottoxgam** [comment]
https://tricorder.pi-hole.net/iktpkgj3x7

I did find this error in /var/log/lighttpd/error.log`2020-09-23 19:33:32: (log.c.217) server started 
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Warning:  Use of undefined constant SQLITE3_OPEN_READWRITE - assumed 'SQLITE3_OPEN_READWRITE' (this will throw an Error in a future version of PHP) in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 26PHP message: PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /var/www/html/admin/scripts/pi-hole/php/database.php:42
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/admin/scripts/pi-hole/php/database.php(65): SQLite3_connect_try('/etc/pihole/gra...', 'SQLITE3_OPEN_RE...', true)
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/admin/scripts/pi-hole/php/groups.php(26): SQLite3_connect('/etc/pihole/gra...', 'SQLITE3_OPEN_RE...')
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: #2 {main}
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 42
2020-09-23 19:33:44: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Warning:  Use of undefined constant SQLITE3_OPEN_READONLY - assumed 'SQLITE3_OPEN_READONLY' (this will throw an Error in a future version of PHP) in /var/www/html/admin/scripts/pi-hole/php/database.php on line 61PHP message: PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in /var/www/html/admin/scripts/pi-hole/php/database.php:42
`

**Comment by dschaper** [comment]
You seem to be using PHP 7.4 on Debian Stretch, which means you've loaded PHP from a custom repository and not the Debian ones. The errors you are seeing are because the needed PHP libraries are not installed.

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the Community Help category.

**Comment by dschaper** [comment]
https://discourse.pi-hole.net Community Help.

**Comment by ottoxgam** [comment]
Huh, news to me! I installed this through the diet-pi manager. I'll post over there. Thanks for the help!
