### ISSUE TITLE
DNS Resolver crash frequently: Error: read ECONNRESET

### ISSUE THREAD

**Issue by kainjinez** [pi-hole/pi-hole#3783]
### Versions

- Pi-hole:  5.1.2
- AdminLTE:  5.1.1
- FTL:  5.2

### Platform

- OS and version:  Ubuntu 20.04

- Platform:  DigitalOcean's Droplet

### Expected behavior

My Pihole show "Lost connection to API" very recently. About 2 times per day.
Screenshot: https://ibb.co/HHMg06C
I see this system log. Please help. Thanks.
```
Oct  6 09:46:58 hostname systemd[1]: Starting PackageKit Daemon...
Oct  6 09:46:58 hostname PackageKit: daemon start
Oct  6 09:46:58 hostname dbus-daemon[584]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Oct  6 09:46:58 hostname systemd[1]: Started PackageKit Daemon.
Oct  6 09:47:04 hostname systemd[1]: apt-daily.service: Succeeded.
Oct  6 09:47:04 hostname systemd[1]: Finished Daily apt download activities.
Oct  6 09:50:01 hostname CRON[625182]: (root) CMD (   PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updatechecker local)
Oct  6 09:50:44 hostname node[586244]: events.js:292
Oct  6 09:50:44 hostname node[586244]:       throw er; // Unhandled 'error' event
Oct  6 09:50:44 hostname node[586244]:       ^
Oct  6 09:50:44 hostname node[586244]: Error: read ECONNRESET
Oct  6 09:50:44 hostname node[586244]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Oct  6 09:50:44 hostname node[586244]: Emitted 'error' event on TLSSocket instance at:
Oct  6 09:50:44 hostname node[586244]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Oct  6 09:50:44 hostname node[586244]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Oct  6 09:50:44 hostname node[586244]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Oct  6 09:50:44 hostname node[586244]:   errno: 'ECONNRESET',
Oct  6 09:50:44 hostname node[586244]:   code: 'ECONNRESET',
Oct  6 09:50:44 hostname node[586244]:   syscall: 'read'
Oct  6 09:50:44 hostname node[586244]: }
Oct  6 09:50:44 hostname systemd[1]: resolver-http.service: Main process exited, code=exited, status=1/FAILURE
Oct  6 09:50:44 hostname systemd[1]: resolver-http.service: Failed with result 'exit-code'.
Oct  6 09:51:04 hostname systemd[1]: resolver-http.service: Scheduled restart job, restart counter is at 15.
Oct  6 09:51:04 hostname systemd[1]: Stopped Resolver over Http.
Oct  6 09:51:04 hostname systemd[1]: Started Resolver over Http.
Oct  6 09:52:03 hostname PackageKit: daemon quit
Oct  6 09:52:03 hostname systemd[1]: packagekit.service: Succeeded.
Oct  6 09:52:59 hostname node[625240]: events.js:292
Oct  6 09:52:59 hostname node[625240]:       throw er; // Unhandled 'error' event
Oct  6 09:52:59 hostname node[625240]:       ^
Oct  6 09:52:59 hostname node[625240]: Error: read ECONNRESET
Oct  6 09:52:59 hostname node[625240]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Oct  6 09:52:59 hostname node[625240]: Emitted 'error' event on TLSSocket instance at:
Oct  6 09:52:59 hostname node[625240]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Oct  6 09:52:59 hostname node[625240]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Oct  6 09:52:59 hostname node[625240]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Oct  6 09:52:59 hostname node[625240]:   errno: 'ECONNRESET',
Oct  6 09:52:59 hostname node[625240]:   code: 'ECONNRESET',
Oct  6 09:52:59 hostname node[625240]:   syscall: 'read'
Oct  6 09:52:59 hostname node[625240]: }
Oct  6 09:52:59 hostname systemd[1]: resolver-http.service: Main process exited, code=exited, status=1/FAILURE
Oct  6 09:52:59 hostname systemd[1]: resolver-http.service: Failed with result 'exit-code'.
Oct  6 09:53:19 hostname systemd[1]: resolver-http.service: Scheduled restart job, restart counter is at 16.
Oct  6 09:53:19 hostname systemd[1]: Stopped Resolver over Http.
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/uyumg8ru0y

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Hello, we will not provide since you are operating an open resolver.
