### ISSUE TITLE
Pihole contains PHP errors

### ISSUE THREAD

**Issue by freebrowser1** [pi-hole/pi-hole#5118]
### Versions
Version:      Pi-hole v5.14.2 FTL v5.20 Web Interface v5.18 
Running on Ubuntu 22.04.1 LTS.

- Pi-hole:  v5.14.2
- AdminLTE:  v5.18 
- FTL:  v5.20

### Platform

- OS and version:  
Ubuntu 22.04.1 LTS.
- Platform:  PHP 8.1.2-1ubuntu2.9 , Apache 2.4.52-1ubuntu4.2

I already installed Apache2.4 and PHP 8.1 earlier on my Pi and later on I installed Pi-hole and it installed successfully. But I can not use it because of HTTP 500 errors which are result of PHP errors of some missing code.
These PHP errors appeared in /var/log/apach2/errors.log.

```
ts/pi-hole/php/database.php:56\nStack trace:\n#0 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#1 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 56, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:18:11.530276 2023] [php:error] [pid 4321] [client 192.168.0.6:55703] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READWRITE" in /var/www/html/admin/scripts/pi-hole/php/groups.php:27\nStack trace:\n#0 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 27, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:18:11.531245 2023] [php:error] [pid 4175] [client 192.168.0.6:55705] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READWRITE" in /var/www/html/admin/scripts/pi-hole/php/groups.php:27\nStack trace:\n#0 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 27, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:18:11.532707 2023] [php:error] [pid 1132] [client 192.168.0.6:55706] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READONLY" in /var/www/html/admin/scripts/pi-hole/php/database.php:56\nStack trace:\n#0 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#1 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 56, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:18:16.549090 2023] [php:error] [pid 1133] [client 192.168.0.6:55709] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READONLY" in /var/www/html/admin/scripts/pi-hole/php/database.php:56\nStack trace:\n#0 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#1 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 56, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:29:32.870747 2023] [php:error] [pid 1132] [client 192.168.0.6:55869] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READWRITE" in /var/www/html/admin/scripts/pi-hole/php/groups.php:27\nStack trace:\n#0 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 27, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:29:32.876340 2023] [php:error] [pid 4175] [client 192.168.0.6:55866] PHP Fatal error:  Uncaught Error: Undefined constant "SQLITE3_OPEN_READWRITE" in /var/www/html/admin/scripts/pi-hole/php/groups.php:27\nStack trace:\n#0 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/groups.php on line 27, referer: http://pi/admin/groups-clients.php
```
I 'fixed' the missing constant SQLITE3_OPEN_READONLY by just setting it to zero (as it does not appear anywhere else in all code) but then there was a missing class SQLite3 which was also defined nowhere.

```
[Sun Jan 15 12:29:32.887730 2023] [php:error] [pid 4321] [client 192.168.0.6:55865] PHP Fatal error:  Uncaught Error: Class "SQLite3" not found in /var/www/html/admin/scripts/pi-hole/php/database.php:43\nStack trace:\n#0 /var/www/html/admin/scripts/pi-hole/php/database.php(60): SQLite3_connect_try()\n#1 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#2 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 43, referer: http://pi/admin/groups-clients.php
[Sun Jan 15 12:29:37.895981 2023] [php:error] [pid 4320] [client 192.168.0.6:55868] PHP Fatal error:  Uncaught Error: Class "SQLite3" not found in /var/www/html/admin/scripts/pi-hole/php/database.php:43\nStack trace:\n#0 /var/www/html/admin/scripts/pi-hole/php/database.php(60): SQLite3_connect_try()\n#1 /var/www/html/admin/api_db.php(28): SQLite3_connect()\n#2 {main}\n  thrown in /var/www/html/admin/scripts/pi-hole/php/database.php on line 43, referer: http://pi/admin/groups-clients.php
```

### Steps to reproduce

Install Pi-hole on a Raspberry Pi with Ubuntu 22.04 and check the javascript element inspector under the console, there appear 500 errors.

**Comment by freebrowser1** [comment]
UPDATE: FIXED !

* php-sqlite3 plugin was not installed
FIX: `sudo apt install php-sqlite3`
* Apache user could not write to sqlite database
FIX: `sudo usermod -a -G pihole www-data` to grant write access by the Apache user.

Now it works.
